In [2]:
import requests
# 
url = "http://127.0.0.1:8000/hybrid_search"
params = {"query": "RAG", "alpha": 0.5}

try:
    response = requests.get(url, params=params)
    if response.status_code == 200:
        print("✅ connection success！API return rsult:")
        print(response.json())
    else:
        print(f"❌ error: API  {response.status_code}")
except Exception as e:
    print(f"❌ can't connect API: {e}")

✅ connection success！API return rsult:
{'query': 'RAG', 'results': ['wall\nfence\npole\ntraffic lig.\ntraffic sig.\nvegetation\nterrain\nperson\ncar\ntruck\nmotorcycle\nbicycle\nMinkowskiNet [8, 49] 54.2 90.6 74.4 84.5 45.3 42.9 52.7 0.5 38.6 87.6 70.3 26.9 87.3 66.0 28.2 17.2\nDeepViewAgg [49] 57.8 93.5 77.5 89.3 53.5 47.1 55.6 18.0 44.5 91.8 71.8 40.2 87.8 30.8 39.6 26.1\nSPT 63.5 93.3 79.3 90.8 56.2 45.7 52.8 20.4 51.4 89.8 73.6 61.6 95.1 79.0 53.1 10.9\nSPT-nano 57.2 91.7 74.7 87.8 49.3 38.8 49.0 12.2 39.2 88.0 69.5 39.9 94.2 80.1 33.7 10.4\nDALES', 'S3DIS\nceiling floor wall beam column\nwindow door chair table bookcase\nsofa board clutter unlabeled\nKITTI-360\nroad sidewalk building wall fence\npole traffic light traffic sign vegetation terrain\nperson car truck motorcycle bicycle\nignored\nDALES\nground vegetation car truck power line\nfence pole building unknown\nFigure A-3: Colormaps.\n18', 'large, diverse, and complex.\nErrors in the Partition. Object boundaries lacking obvi-\nous discontinuities, such as curbs vs. roads or whiteboards\nvs. walls, are not well recovered by our partition. As parti-\ntion errors cannot be corrected with our approach, this may\nlead to classification errors. To improve this, we could re-\nplace our handcrafted point descriptors (Section A-4) with\nfeatures directly learned for partitioning [26, 23]. However,']}

In [4]:
import pandas as pd

# 1. 
queries = [
    "What is hybrid retrieval?",
    "What are the advantages of the model proposed in the paper?",
    "How to optimize the FAISS index?"
]
# 2. 
def run_evaluation(queries):
    eval_results = []
    
    for q in queries:
        # adjust alpha from 0.1-0.9
        response = requests.get(f"http://127.0.0.1:8000/hybrid_search", params={"query": q, "alpha": 0.5})
        
        if response.status_code == 200:
            data = response.json()
            # analysis
            eval_results.append({
                "query": q,
                "result": str(data.get("results", "No results")),
                "status": "Success"
            })
        else:
            eval_results.append({"query": q, "result": None, "status": "Failed"})
            
    return pd.DataFrame(eval_results)

# 3. 
df_results = run_evaluation(queries)
print("result---:")
print(df_results)

result---:
                                               query  \
0                          What is hybrid retrieval?
1  What are the advantages of the model proposed ...
2                   How to optimize the FAISS index?

                                              result   status
0  ['by adding the dist-Pi supervision. This illu...  Success
1  ['and model size. This approach particularly b...  Success
2  ['In particular, We chose λ1 such that |P1|/|P...  Success

In [ ]:
import requests
import pandas as pd

# query key setting


# 設定關鍵字
ground_truth = [
    {
        "query": "How are pose features defined for each superpoint?", 
        "keywords": ["normal vector", "principal component", "cosine"]
    },
    {
        "query": "What are the limitations of superpoint-based methods?", 
        "keywords": ["preprocessing", "costly", "expressivity"]
    }
]

def calculate_precision_at_k(results, keywords):
    # 
    hits = sum(1 for kw in keywords if kw in str(results))
    return hits / len(keywords)

results_log = []

for item in ground_truth:
    response = requests.get("http://127.0.0.1:8000/hybrid_search", params={"query": item['query']})
    if response.status_code == 200:
        data = response.json()
        score = calculate_precision_at_k(data['results'], item['keywords'])
        results_log.append({"query": item['query'], "score": score, "raw": data['results']})

# 顯示評測報告
df = pd.DataFrame(results_log)
print("score report:")
display(df[['query', 'score']])

評測分數報告:

                                               query  score
0  How are pose features defined for each superpo...    1.0
1  What are the limitations of superpoint-based m...    1.0

In [18]:
# 
ground_truth = [
    {"query": "What are the core principles of RAG?", "keywords": ["Retrieval", "Generation"]},
    {"query": "How to optimize the FAISS index?", "keywords": ["FAISS", "index"]},
]

def calculate_precision_at_k(results, keywords):
    # compaer content
    content = str(results).lower()
    hits = sum(1 for kw in keywords if kw.lower() in content)
    return hits / len(keywords)

results_log = []

for item in ground_truth:
    response = requests.get("http://127.0.0.1:8000/hybrid_search", params={"query": item['query']})
    if response.status_code == 200:
        data = response.json()
        score = calculate_precision_at_k(data['results'], item['keywords'])
        results_log.append({"query": item['query'], "score": score, "raw": data['results']})

# 顯示評測報告
import pandas as pd
df = pd.DataFrame(results_log)
print("評測分數報告:")
display(df[['query', 'score']])

print(results_log[0]['raw'])

評測分數報告:

                                  query  score
0  What are the core principles of RAG?    0.0
1      How to optimize the FAISS index?    0.0

['lengths, surfaces, volumes, and point counts.\n• Pose features (7): For each superpoint, we define a nor-\nmal vector as its principal component with the smallest\neigenvalue. We then characterize the relative position\nbetween two superpoints with the cosine of the angle\nbetween the superpoint normal vectors (dim: 1) and\nbetween each of the two superpoints’ normal and the\nmean offset direction (dim: 2). Additionally, the off-\nset between the centroids of the superpoints is used to', 'However, superpoint-based methods often require a costly\npreprocessing step, and their range and expressivity are lim-\n1\narXiv:2306.08045v2  [cs.CV]  12 Aug 2023', 'wall\nfence\npole\ntraffic lig.\ntraffic sig.\nvegetation\nterrain\nperson\ncar\ntruck\nmotorcycle\nbicycle\nMinkowskiNet [8, 49] 54.2 90.6 74.4 84.5 45.3 42.9 52.7 0.5 38.6 87.6 70.3 26.9 87.3 66.0 28.2 17.2\nDeepViewAgg [49] 57.8 93.5 77.5 89.3 53.5 47.1 55.6 18.0 44.5 91.8 71.8 40.2 87.8 30.8 39.6 26.1\nSPT 63.5 93.3 79.3 90.8 56.2 45.7 52.8 20.4 51.4 89.8 73.6 61.6 95.1 79.0 53.1 10.9\nSPT-nano 57.2 91.7 74.7 87.8 49.3 38.8 49.0 12.2 39.2 88.0 69.5 39.9 94.2 80.1 33.7 10.4\nDALES']

In [ ]:
# 
print(f"目前儲存的結果數量: {len(results_log)}")
print("原始資料內容:")
print(results_log)

目前儲存的結果數量: 2
原始資料內容:
[{'query': 'What are the core principles of RAG?', 'score': 0.0, 'raw': ['lengths, surfaces, volumes, and point counts.\n• Pose features (7): For each superpoint, we define a nor-\nmal vector as its principal component with the smallest\neigenvalue. We then characterize the relative position\nbetween two superpoints with the cosine of the angle\nbetween the superpoint normal vectors (dim: 1) and\nbetween each of the two superpoints’ normal and the\nmean offset direction (dim: 2). Additionally, the off-\nset between the centroids of the superpoints is used to', 'However, superpoint-based methods often require a costly\npreprocessing step, and their range and expressivity are lim-\n1\narXiv:2306.08045v2  [cs.CV]  12 Aug 2023', 'wall\nfence\npole\ntraffic lig.\ntraffic sig.\nvegetation\nterrain\nperson\ncar\ntruck\nmotorcycle\nbicycle\nMinkowskiNet [8, 49] 54.2 90.6 74.4 84.5 45.3 42.9 52.7 0.5 38.6 87.6 70.3 26.9 87.3 66.0 28.2 17.2\nDeepViewAgg [49] 57.8 93.5 77.5 89.3 53.5 47.1 55.6 18.0 44.5 91.8 71.8 40.2 87.8 30.8 39.6 26.1\nSPT 63.5 93.3 79.3 90.8 56.2 45.7 52.8 20.4 51.4 89.8 73.6 61.6 95.1 79.0 53.1 10.9\nSPT-nano 57.2 91.7 74.7 87.8 49.3 38.8 49.0 12.2 39.2 88.0 69.5 39.9 94.2 80.1 33.7 10.4\nDALES']}, {'query': 'How to optimize the FAISS index?', 'score': 0.0, 'raw': ['In particular, We chose λ1 such that |P1|/|P0 ∼ 30 in our\nexperiments.\nWe first define ˆG0 as the point-level adjacency graph ˆG\nand f0 as f. We can now define the levels of a hierarchical\npartition Pi for i ∈ [1, I]:\nfi, Pi, ˆGi := partition( arg min\ne∈RD×|Pi−1 |\nJ\n\x10\ne; fi−1, ˆGi−1, λi−1\n\x11\n).\n(A-5)\nGiven that the optimization problems defined in Eq. (A-5)\nfor i > 1 operate on the component graphs ˆGi, which are\nsmaller than ˆG0, the first partition is the most demanding in', 'Table A-7: Class-wise Performance. Class-wise mIoU across all datasets for our Superpoint Transformer .\nS3DIS Area 5\nMethod mIoU ceiling floor wall beam column window door chair table bookcase sofa board clutter\nPointNet [42] 41.1 88.8 97.3 69.8 0.1 3.9 46.3 10.8 52.6 58.9 40.3 5.9 26.4 33.2\nSPG [29] 58.4 89.4 96.9 78.1 0.0 42.8 48.9 61.6 84.7 75.4 69.8 52.6 2.1 52.2\nMinkowskiNet [8] 65.4 91.8 98.7 86.2 0.0 34.1 48.9 62.4 81.6 89.8 47.2 74.9 74.4 58.6', 'Table 2: Performance Evaluation. We report the Mean\nIntersection-over-Union of different methods on three dif-\nferent datasets. SPT performs on par or better than recent\nmethods with significantly fewer parameters. † superpoint-\nbased. ⋆/∗ model with 777k/70k parameters.\nModel Size S3DIS KITTI DALES×106 6-Fold Area 5 360 val\nPointNet++ [43] 3.0 56.7 - - 68.3\n† SPG [29] 0.28 62.1 58.0 - 60.6\nConvPoint [4] 4.7 68.2 - - 67.4\n† SPG + SSP [26] 0.29 68.4 61.7 - -\n† SPNet [23] 0.32 68.7 - - -']}]

In [ ]:
import sqlite3


conn = sqlite3.connect("data/paper.db")
cursor = conn.cursor()
cursor.execute("SELECT count(*) FROM docs") # 
count = cursor.fetchone()[0]
print(f"資料庫內目前的總筆數: {count}")

if count > 0:
    cursor.execute("SELECT content FROM docs LIMIT 1")
    print("範例:", cursor.fetchone()[0][:100]) # before 100word
else:
    print("❌ entrpy db ingest.py")
conn.close()

資料庫內目前的總筆數: 155
範例: Efficient 3D Semantic Segmentation with Superpoint Transformer
Damien Robert1, 2
damien.robert@ign.f

In [13]:
# 
response = requests.get(url, params={"query": "RAG", "alpha": 0.5})

if response.status_code == 200:
    data = response.json()
    print("--- search by system ---")
    print(data['results'])  # 
else:
    print(f"API fale，error code: {response.status_code}")

--- search by system ---
['wall\nfence\npole\ntraffic lig.\ntraffic sig.\nvegetation\nterrain\nperson\ncar\ntruck\nmotorcycle\nbicycle\nMinkowskiNet [8, 49] 54.2 90.6 74.4 84.5 45.3 42.9 52.7 0.5 38.6 87.6 70.3 26.9 87.3 66.0 28.2 17.2\nDeepViewAgg [49] 57.8 93.5 77.5 89.3 53.5 47.1 55.6 18.0 44.5 91.8 71.8 40.2 87.8 30.8 39.6 26.1\nSPT 63.5 93.3 79.3 90.8 56.2 45.7 52.8 20.4 51.4 89.8 73.6 61.6 95.1 79.0 53.1 10.9\nSPT-nano 57.2 91.7 74.7 87.8 49.3 38.8 49.0 12.2 39.2 88.0 69.5 39.9 94.2 80.1 33.7 10.4\nDALES', 'S3DIS\nceiling floor wall beam column\nwindow door chair table bookcase\nsofa board clutter unlabeled\nKITTI-360\nroad sidewalk building wall fence\npole traffic light traffic sign vegetation terrain\nperson car truck motorcycle bicycle\nignored\nDALES\nground vegetation car truck power line\nfence pole building unknown\nFigure A-3: Colormaps.\n18', 'large, diverse, and complex.\nErrors in the Partition. Object boundaries lacking obvi-\nous discontinuities, such as curbs vs. roads or whiteboards\nvs. walls, are not well recovered by our partition. As parti-\ntion errors cannot be corrected with our approach, this may\nlead to classification errors. To improve this, we could re-\nplace our handcrafted point descriptors (Section A-4) with\nfeatures directly learned for partitioning [26, 23]. However,']

In [16]:

response = requests.get("http://127.0.0.1:8000/hybrid_search", params={"query": "What are the core principles of RAG?", "alpha": 0.5})
results = response.json().get('results', [])

print("--- content---")
for i, chunk in enumerate(results):
    print(f"[{i}] {chunk}")

# 2. 
keywords = ["Retrieval", "Generation"]
for chunk in results:
    found = [kw for kw in keywords if kw.lower() in chunk.lower()]
    print(f"key word: {found}")

--- content---
[0] lengths, surfaces, volumes, and point counts.
• Pose features (7): For each superpoint, we define a nor-
mal vector as its principal component with the smallest
eigenvalue. We then characterize the relative position
between two superpoints with the cosine of the angle
between the superpoint normal vectors (dim: 1) and
between each of the two superpoints’ normal and the
mean offset direction (dim: 2). Additionally, the off-
set between the centroids of the superpoints is used to
[1] However, superpoint-based methods often require a costly
preprocessing step, and their range and expressivity are lim-
1
arXiv:2306.08045v2  [cs.CV]  12 Aug 2023
[2] wall
fence
pole
traffic lig.
traffic sig.
vegetation
terrain
person
car
truck
motorcycle
bicycle
MinkowskiNet [8, 49] 54.2 90.6 74.4 84.5 45.3 42.9 52.7 0.5 38.6 87.6 70.3 26.9 87.3 66.0 28.2 17.2
DeepViewAgg [49] 57.8 93.5 77.5 89.3 53.5 47.1 55.6 18.0 44.5 91.8 71.8 40.2 87.8 30.8 39.6 26.1
SPT 63.5 93.3 79.3 90.8 56.2 45.7 52.8 20.4 51.4 89.8 73.6 61.6 95.1 79.0 53.1 10.9
SPT-nano 57.2 91.7 74.7 87.8 49.3 38.8 49.0 12.2 39.2 88.0 69.5 39.9 94.2 80.1 33.7 10.4
DALES
key word: []
key word: []
key word: []